root: true

parser: '@typescript-eslint/parser'

plugins:
  - '@typescript-eslint'

extends:
  - 'eslint:recommended'

rules:
  'comma-dangle':
    - 1
    - 'always-multiline'
  'quotes':
    - 1
    - 'single'

overrides:
  - files:
    - 'src/**/*.ts'

    extends:
      - 'plugin:@typescript-eslint/recommended'

    rules:
      '@typescript-eslint/no-explicit-any':
        - 0
      '@typescript-eslint/no-non-null-assertion':
        - 0
      '@typescript-eslint/no-unused-vars':
        - 1
        - argsIgnorePattern: '^_'
          varsIgnorePattern: '^_'
