root: true

parser: '@typescript-eslint/parser'

plugins:
  - '@typescript-eslint'

extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'

rules:
  'comma-dangle':
    - 1
    - 'always-multiline'
  'quotes':
    - 1
    - 'single'
  '@typescript-eslint/no-explicit-any':
    - 0
  '@typescript-eslint/no-unused-vars':
    - 1
    - argsIgnorePattern: '^_'
      varsIgnorePattern: 'Resolver$'
  '@typescript-eslint/no-var-requires':
    - 0
